---

- hosts: all
  become: true
  become_user: root

  tasks:
    - name: Pull helloworld
      docker:
        name: Helloworld 
        image: hello-world
        state: running
        ports: 8080:80 

